/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Fragment: typeof import('react').Fragment
  const Icon: typeof import('@iconify/react').Icon
  const Link: typeof import('react-router-dom').Link
  const NavLink: typeof import('react-router-dom').NavLink
  const Navigate: typeof import('react-router-dom').Navigate
  const Outlet: typeof import('react-router-dom').Outlet
  const ProgressContext: typeof import('./src/shared/hooks/useProgress').ProgressContext
  const RequireAuth: typeof import('./src/widgets/auth/RequireAuth').RequireAuth
  const Route: typeof import('react-router-dom').Route
  const Routes: typeof import('react-router-dom').Routes
  const Suspense: typeof import('react').Suspense
  const apiErrorMessage: typeof import('./src/shared/api/errorDisplay').apiErrorMessage
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const create: typeof import('zustand').create
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const dayjs: typeof import('dayjs').default
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useHref: typeof import('react-router-dom').useHref
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInRouterContext: typeof import('react-router-dom').useInRouterContext
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useLinkClickHandler: typeof import('react-router-dom').useLinkClickHandler
  const useLocation: typeof import('react-router-dom').useLocation
  const useMemo: typeof import('react').useMemo
  const useMessage: typeof import('./src/shared/hooks/useMessage').useMessage
  const useNavigate: typeof import('react-router-dom').useNavigate
  const useNavigationType: typeof import('react-router-dom').useNavigationType
  const useNotification: typeof import('./src/shared/hooks/useNotification').useNotification
  const useOptimistic: typeof import('react').useOptimistic
  const useOutlet: typeof import('react-router-dom').useOutlet
  const useOutletContext: typeof import('react-router-dom').useOutletContext
  const useParams: typeof import('react-router-dom').useParams
  const useProgress: typeof import('@bprogress/react').useProgress
  const useQuery: typeof import('@tanstack/react-query').useQuery
  const useQueryClient: typeof import('@tanstack/react-query').useQueryClient
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useResolvedPath: typeof import('react-router-dom').useResolvedPath
  const useRoutes: typeof import('react-router-dom').useRoutes
  const useSearchParams: typeof import('react-router-dom').useSearchParams
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const withAuth: typeof import('./src/widgets/auth/withAuth').withAuth
  const withMessage: typeof import('./src/shared/hooks/useMessage').withMessage
  const withNotification: typeof import('./src/shared/hooks/useNotification').withNotification
  const withProgress: typeof import('./src/shared/hooks/useProgress').withProgress
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ReactNode } from 'react'
  import('react')
  // @ts-ignore
  export type { QueryRequest } from './src/shared/api/request'
  import('./src/shared/api/request')
  // @ts-ignore
  export type { PageResponse, ServerResponse, ErrorResponse } from './src/shared/api/response'
  import('./src/shared/api/response')
}
